# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 01:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_alert', models.BooleanField()),
                ('email_alert_email', models.CharField(blank=True, max_length=200)),
                ('text_message_alert', models.BooleanField()),
                ('text_message_alert_phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer')),
            ],
        ),
    ]
