# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('purchase_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt', models.URLField(max_length=250)),
            ],
        ),
    ]
